### ISSUE TITLE
Render Prop for Nodes and Links

### ISSUE THREAD

**Issue by baldwmic** [uber/react-vis-force#23]
First off, this library is brilliant! I love the idea of using React's declarative approach with d3.js.

I'm wondering how you feel about adding props for rendering the nodes and links of the graph? There could be a default prop for each, but the main idea would be to allow a consumer of this library to define their own Node and Link components and pass those in to the render props.

For instance, `ForceGraphNode` could accept something like this
```
const Node = (props) => {
  return (
    <rect
        {...props}
      />
  );
}

<ForceGraphNode node={{ id: 'custom-node', label: 'Custom node' }} render={Node} />
```

This would require decoupling the specific rendering of svg elements like is being done with [`ForceGraphNode`](https://github.com/uber/react-vis-force/blob/a4f6cd095bc1eb5ec8ccdda3cfd25d48415bae49/src/components/ForceGraphNode.js#L61) and [`ForceGraphLink`](https://github.com/uber/react-vis-force/blob/a4f6cd095bc1eb5ec8ccdda3cfd25d48415bae49/src/components/ForceGraphLink.js#L45) in favor of enabling custom Node or Link components.

**Comment by fastfrwrd** [comment]
Yep! So this actually *should* be working after the next release with the current code in master (h/t @rarous, #21), but any component with a `link` prop will be rendered as a link, same with `node`.

```javascript
const MyCustomNode = props => (
  <rect {...props} />
);

const App = () => ( 
  <ForceGraph>
    <MyCustomNode node={{id: 'custom-node', label: 'Custom node'}} />
  </ForceGraph>
);
```

**Comment by baldwmic** [comment]
Thank you for the update! I think the code is still coupled to rendering circles specifically, but it works to render a rectangle.

## Custom Node Implementation
```
const CustomNode = (props) => {
  const {
    node, className,
    cx, cy,
    ...spreadable,
  } = props;

  return (
    <rect
      className={`rv-force__node ${className}`}
      x={cx}
      y={cy}
      {...spreadable}
    />
  );
}

<CustomNode node={{ id: 'first-node' }} width={10} height={10} fill="#11939A" />
```

## Issues
- We must specifically pull out the `cx` and `cy` properties since a SVG circle expects those, but a SVG rectangle expects `x` and `y`.

- A circle takes an origin of `cx` and `cy` and it's radius (`r`) expands out in all directions from that central point. But, a rectangle takes an origin of `x` and `y` and expands both right (`width`) and down (`height`) from that point.

With the following code we can see this problem in how the graph is rendered.

```
<ForceGraph>
  <CustomNode node={{ id: 'first-node' }} width={10} height={10} fill="#11939A" />
  <ForceGraphNode node={{ id: 'second-node' }} fill="#47d3d9" />,
  <ForceGraphLink link={{ source: 'first-node', target: 'second-node' }} />,
</ForceGraph>
```

<img width="220" alt="screen shot 2016-12-07 at 23 35 12" src="https://cloud.githubusercontent.com/assets/10538297/20997680/dbb983f8-bcd5-11e6-9fb0-d72ff78e2c66.png">

## Next Steps
If you're looking for PRs, I'd be willing to work on decoupling / improving the rendering logic to allow for more than just circles to render properly.

**Comment by fastfrwrd** [comment]
Interesting, I like the idea of decoupling this if it's not too odd. My two cents: cx, cy, height, and width aren't the worst values to get back. Just some simple geometry calculations at that point, no matter the desired shape. Maybe we should just be less opinionated and provide some common SVG element wrappers, like ForceNodeRect, ForceNodePath, etc.

**Comment by baldwmic** [comment]
Good point, I like that approach. I'm just now to the point where I'm starting to use `react-vis-force`, so I will see whether that influences how I would approach this PR.
