### ISSUE TITLE
master <> latest release

### ISSUE THREAD

**Issue by TobiasHauck** [uber/react-vis-force#25]
I wonder if there is any reason why the latest code on master is not released on npm?
I need some of the new functionalities, so I'd be very happy to download them via npm install.

Thank you & keep up good work!

**Comment by nikordaris** [comment]
That would explain why my custom node didn't work. I forked to implement it only to discover it already exists. Is this still being maintained @fastfrwrd ? Can we get the latest master pushed to npm?

**Comment by xiaosansiji** [comment]
Maybe the latest version needs more detailed doc? I would like to help  to perfect it~

**Comment by fastfrwrd** [comment]
sorry about this - latest version was just released as 0.2.0.
