### ISSUE TITLE
Larger network animation/interaction performance

### ISSUE THREAD

**Issue by matt-erhart** [uber/react-vis-force#26]
I just tested a network ~3 to 4 times larger than the les mis network, and I noticed some significant slow downs in animation and interaction responsiveness relative to my d3-only implementation. Were you able to get performance equal to d3-only somehow? Is there a hard limit on the network size react-d3 can handle?

**Comment by fastfrwrd** [comment]
this is definitely true for us across the board. we're planning to experiment with working with the react-vis team to try to fix some of our rendering issues, as they have recently implemented full support for the force-directed graphs in their library.

**Comment by JimmyMow** [comment]
Any update on this? I am having serious performance issues with a data set size of ~500 links and ~200 nodes

**Comment by matt-erhart** [comment]
I just did it myself with webgl. Canvas should work given the number of elements you've got.

**Comment by JimmyMow** [comment]
@matt-erhart do you have a code example or anything I can look at? Would be super helpful. Thanks

**Comment by JimmyMow** [comment]
@fastfrwrd any resources or places you can point me to? This library is great but performance has become an issue. I'm dealing with `~407 nodes` and `~507` edges.
