### ISSUE TITLE
Fix <ForceGraphArrowLink /> components

### ISSUE THREAD

**Issue by kirill-konshin** [uber/react-vis-force#27]
Since links are defined as `source` and `target` is it possible to show the direction on links? Some additional prop can be introduced to enable that.

**Comment by nikordaris** [comment]
I would presume ForceGraphArrowLink does this?

**Comment by kirill-konshin** [comment]
Is it included in 0.1.4? I can't find it in NPM package.

**Comment by nikordaris** [comment]
Doesn't look like it. Issue #25 has requested the latest get published.

**Comment by fastfrwrd** [comment]
Arrow Links were contributed in, but don't seem to be doing the trick on the storybook docs. Marking as help wanted to get the arrow links working.

**Comment by kirill-konshin** [comment]
I've tried, they just don't show up completely :(

**Comment by fastfrwrd** [comment]
@kirill-konshin would appreciate your input on the branch I just opened, it should make the arrows work.

**Comment by kirill-konshin** [comment]
@fastfrwrd sure, but how should I install it? Repository has to be built before usage... Can you publish a beta version (like `0.2.1-beta.0`) to NPM under your personal scope `@fastfrwrd/react-vis-force`?

**Comment by fastfrwrd** [comment]
I'll get this released today or tomorrow - it should definitely work a bit better for you, it worked well on storyboard. you may find there need to be slight alterations to the component to make it more flexible, so PR those in if they are necessary.

**Comment by kirill-konshin** [comment]
Sure, today/tomorrow is perfect, I'll wait.

**Comment by fastfrwrd** [comment]
fix is in 0.3.0

**Comment by kirill-konshin** [comment]
Fix confirmed.
