### ISSUE TITLE
Missing function to deselect a currently selected node

### ISSUE THREAD

**Issue by kirill-konshin** [uber/react-vis-force#29]
Assume that `defaultSelectedNode` is set, then even if it will be later set to `null` the node will still be highlighted.

**Comment by fastfrwrd** [comment]
This mimics the behavior of other `default*` props in react such as [defaultValue](https://facebook.github.io/react/docs/uncontrolled-components.html) for inputs. We probably want to introduce a controller paradigm as the fix to this, which would expose a `selectedNode` prop which can control an `InteractiveForceGraph`.

**Comment by kirill-konshin** [comment]
Exactly. There has to be just a `selectedNode` prop, which can be dynamically assigned or unassigned by the controller.

**Comment by fastfrwrd** [comment]
fix is in 0.3.0

**Comment by kirill-konshin** [comment]
Fix confirmed.
