### ISSUE TITLE
Zoom panLimit prematurely prevents panning

### ISSUE THREAD

**Issue by nikordaris** [uber/react-vis-force#30]
When my canvas is smaller than the size of the graph at scale: 1, the panLimit sets the pan border too short creating a user experience that prevents the user from panning to see all of the graph at certain zoom levels. I'm not entirely sure why a pan limit is needed other than to prevent the user from panning the graph entirely off the visible screen and losing track of where the graph is. In my opinion given the funky behavior of the pan limit, I would opt for unlimited panning. I'm not sure how to fix this because it seems you would need to tell the ZoomableSVGGroup component where your graph border is and the pan limit would need to use that instead of the canvas width and height to calculate the pan limit.

**Comment by fastfrwrd** [comment]
fix is in 0.3.0
